#!/bin/bash

# Run archcraft-hooks related commands.

Lsb_release() {
    local file=/etc/lsb-release

    if [[ -z "`grep "^DISTRIB_RELEASE=" $file`" ]] ; then
        # add missing DISTRIB_RELEASE=
        echo "DISTRIB_RELEASE=rolling" >> "$file"
    fi
    sed -i "$file" \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=Archcraft|' \
        -e 's|^DISTRIB_RELEASE=.*$|DISTRIB_RELEASE=rolling|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"Archcraft\"|'
}

Os_release() {
    local file=/usr/lib/os-release

    sed -i "$file" \
        -e 's|^NAME=.*$|NAME=\"Archcraft\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"Archcraft\"|' \
        -e 's|^ID=.*$|ID=archcraft|' \
        -e 's|^ID_LIKE=.*$|ID_LIKE=arch|' \
        -e 's|^BUILD_ID=.*$|BUILD_ID=rolling|' \
        -e 's|^HOME_URL=.*$|HOME_URL=\"https://archcraft.io\"|' \
        -e 's|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL=\"https://archcraft.io/blog\"|' \
        -e 's|^SUPPORT_URL=.*$|SUPPORT_URL=\"https://discord.gg/GvKcCCPXA6\"|' \
        -e 's|^BUG_REPORT_URL=.*$|BUG_REPORT_URL=\"https://github.com/archcraft-os/archcraft/issues\"|' \
        -e 's|^LOGO=.*$|LOGO=archcraft|'

    if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi
}

Issues() {
    sed -i 's|Arch Linux|Archcraft|g' /etc/issue /usr/share/factory/etc/issue
}

Main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  Os_release ;;
        lsb-release) Lsb_release ;;
        "")          Os_release
                     Lsb_release
                     Issues
                     ;;
    esac
}

Main "$@"
